version: '3.8'

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=services_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - services-network
      
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - services-network

  user-app:
    build: ./user_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/services_db
      - JWT_SECRET_KEY=secret_key
      - JWT_ALGORITHM=HS256
    depends_on:
      - database
    networks:
      - services-network
    restart: on-failure:5

  service-app:
    build: ./service_app
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET_KEY=secret_key
      - JWT_ALGORITHM=HS256
    depends_on:
      - user-app
    networks:
      - services-network

  order-app:
    build: ./order_app
    ports:
      - "8002:8002"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DATABASE_NAME=services_db
      - JWT_SECRET_KEY=secret_key
      - JWT_ALGORITHM=HS256
      - SERVICE_SERVICE_URL=http://localhost:8001
      - USER_SERVICE_URL=http://localhost:8000
    depends_on:
      - mongo
      - user-app
      - service-app
    networks:
      - services-network

networks:
  services-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: