version: '3'

services:
  user-app:
    build: ./user_app
    ports:
      - "8000:8000"
    networks:
      - app-network

  service-app:
    build: ./service_app
    ports:
      - "8001:8001"
    depends_on:
      - user-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
